markdown: kramdown
sass:
  style: compressed
excerpt_separator: <!-- more -->
permalink: pretty

theme: deathwish-md-theme

plugins:
  - jekyll-seo-tag

exclude:
  - vendor
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - deathwish-md-theme.gemspec
